<?xml version="1.0" encoding="ASCII"?>
<Artifact:Artifact xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Artifact="http://documentum.emc.com/infrastructure/12012007/artifact" xmlns:moduledef="http://documentum.emc.com/artifact/12012007/moduledef" urn="urn:com.emc.ide.artifact.moduledef/customfoldertbo?artifactURI=file:/C:/Users/akoshy/IdeaProjects/docapp/Artifacts/Modules/customfoldertbo.module" categoryId="com.emc.ide.artifact.moduledef">
  <dataModel xsi:type="moduledef:ModuleDef" objectName="customfoldertbo" a_module_type="TBO">
    <objectType href="urn:com.emc.ide.artifact.dclass/dmc_module?name=dmc_module#//@dataModel"/>
    <interfaceJars href="urn:com.emc.ide.artifact.jardef.jardef/customfoldertbojardef?artifactURI=file:/C:/Users/akoshy/IdeaProjects/dctm-docapp/Artifacts/JAR%20Definitions/customfoldertbojardef.jardef#//@dataModel"/>
    <implementationJars href="urn:com.emc.ide.artifact.jardef.jardef/customfoldertboimpl?artifactURI=file:/C:/Users/akoshy/IdeaProjects/dctm-docapp/Artifacts/JAR%20Definitions/customfoldertboimpl.jardef#//@dataModel"/>
    <runtimeEnvironmentXML objectName="RuntimeEnvironment.xml">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_sysobject?name=dm_sysobject#//@dataModel"/>
      <log/>
    </runtimeEnvironmentXML>
    <primaryElement primary_class="ak.dctm.impl.MySop"/>
    <thirdPartyLibraries href="urn:com.emc.ide.artifact.jardef.javalibrary/commonlibrary?artifactURI=file:/C:/Users/akoshy/IdeaProjects/dctm-docapp/Artifacts/Java%20Libraries/commonlibrary.javalibrary#//@dataModel"/>
    <miscellaneous objectName="Miscellaneous">
      <objectType href="urn:com.emc.ide.artifact.dclass/dm_folder?name=dm_folder#//@dataModel"/>
    </miscellaneous>
  </dataModel>
  <viewModel xsi:type="Artifact:DefaultArtifactViewModel"/>
</Artifact:Artifact>
